//Script GUID:2e0a8aae-dda6-4671-aa82-54b3c553a5e3
//Used for tracking history

MODULE @"/shares/AzureAnalytics.Prod/Sdk/AzureAnalytics1.3.module" AS AzureAnalytics;

//#DECLARE StartDate string = @"2019-11-28 00:00";
//#DECLARE EndDate string = @"2019-11-29 00:00";
#DECLARE StartDate string = @@startDateTime@@;
#DECLARE EndDate string = @@endDateTime@@;
#DECLARE JobFrequency string = @"1440";
#DECLARE ExpiryInDays string = @"730";
#DECLARE StartDateTime DateTime = DateTime.Parse(@StartDate);

#DECLARE IoTEdgeStream string = "Microsoft.Cloud.AzureSRE.AzureIoTEdge";
#DECLARE Stage string = "PPE";

//https://aad.cosmos11.osdinfra.net/cosmos/AzureSRE/shares/AzureAnalytics.Data1/AzureAnalytics.Data1.PublishedData/Microsoft.Cloud.AzureSRE.AzureIoTEdge/P360EdgeActiveDevicesPROD/2019/11/Data_2019_11_14.ss?property=info
#DECLARE DevicesStream string = @IoTEdgeStream + ".P360EdgeActiveDevices" + @Stage;
AzureAnalytics.Initialize
(
    entity = @DevicesStream
);
deviceInfo =
    AzureAnalytics.LoadStream
    (
        entity = @DevicesStream,
        startDateTime = @StartDate,
        endDateTime = @EndDate
    );

deviceInfo = SELECT TOP 10 *;
stream = SELECT @StartDateTime AS StartDate, ARRAY_AGG(resourceId) AS resourceIds FROM deviceInfo;

stream =
    SELECT StartDate,
           "Public" AS CloudType,
           StartDate AS PreciseTimeStamp,
           "" AS Tenant,
           "" AS TenantName,
           "" AS Role,
           "" AS RoleInstance,
           "" AS EventId,
           "EdgeRuntimeDiagnostics" AS metricName,
           "" AS metadataReference,
           "FakeHub" AS dimIotHubName,
           "" AS dimIotHubArmResourceId,
           "FakeSubscription" AS dimSubscriptionId,
           metric.Name AS dimKey1,
           metric.Tags AS dimKey2,
           metric.DeviceId AS dimKey3,
           "" AS dimKey4,
           "" AS dimKey5,
           "" AS dimKey6,
           "" AS dimKey7,
           metric.TimeGeneratedUtc.Ticks AS metricValue1,
           0 AS metricValue2,
           0 AS metricValue3,
           0 AS metricValue4,
           0 AS metricValue5,
           0 AS metricValue6,
           0 AS metricValue7,
           0 AS metricValue8,
           0 AS metricValue9,
           0 AS metricValue10,
           metric.Value AS metricValue11,
           0 AS metricValue12,
           0 AS metricValue13,
           0 AS metricValue14
    FROM stream
         CROSS APPLY GenerateMetrics.GenerateSeries(@StartDateTime, resourceIds) AS metric;

AzureAnalytics.PublishStream
(
    entity = "Microsoft.Azure.SRE.OI.lefitche.P360.testdata5",
    startDateTime = @StartDate,
    periodInMinutes = @JobFrequency,
    input = stream,
    clusteredBy = "metricName",
    sortedBy = "StartDate",
    expiryInDays = @ExpiryInDays
); 